# fly.toml file generated for squadbot on 2022-11-30T00:13:04-05:00

app = "squadbot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.machine_checks]]
    image = "alpine:latest"
    entrypoint = ["/bin/sh", "-c"]
    command = ["grep", "health-check.txt", "|", "grep", "Hello, World!"]
    kill_signal = "SIGKILL"
    kill_timeout = "5s"
